name: rseq
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - pylint
  - pytest
  - r-reutils
  - r-tidyverse
  - r-jsonlite
  - bioconductor-rsamtools
  - r-xml
  - boa
  - snakemake
  - conda-build
  - graphviz
  - samtools
