name: rseq
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - pylint
  - pytest
  # The last version with cores working correctly in api
  # TODO: submit an issue about this...
  - snakemake-minimal=6.4.0
  # Boa is required for conda mambabuild
  - boa
  - graphviz
  - pandas==1.2.0
  - click
  - pysradb
