name: rseq
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - pylint
  - pytest
  - snakemake-minimal
  # Boa is required for conda mambabuild
  - boa
  - graphviz
  - pandas==1.2.0
  - click
  - pysradb
