{% set name = "RSeq" %}
{% set version = "0.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ../../RSeq
#  git_url: https://github.com/millerh1/conda-testing.git
#  git_rev: v1.4
#  git_depth: 5

requirements:
  run:
    - r-reutils
    - r-tidyverse
    - r-jsonlite
    - bioconductor-rsamtools
    - r-xml
    - snakemake
    - graphviz

test:
  commands:
    - RSeq


