{% set name = "rseq" %}
{% set version = "0.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ../
#  git_url: https://github.com/Bishop-Laboratory/RSeq.git
#  git_rev: v0.0.1
#  git_depth: 8

requirements:
  build:
    - python >=3.6
    - setuptools
    - click
    - pysradb
    - pysam
    # Have to set this verion or causes install error due to incompatibility with pysradb
    - pandas==1.2.0
  run:
    - python >=3.6
    - graphviz
    - snakemake-minimal
    - click
    - pysradb
    - pysam
    # Have to set this verion or causes install error due to incompatibility with pysradb
    - pandas==1.2.0
