# This is a basic workflow to help you get started with Actions

name: setup_miniconda_basic

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    branches:
      - init_ci
  # Triggers the workflow on push or pull request events but only for the main branch
  #push:
  #  branches: [ main ]
  #pull_request:
  #  branches: [ main ]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # On this example an environment named "test" will be created with the specific python-version installed for each opearating system, resulting on 6 build workers.
  example-1:
    name: Ex1 (${{ matrix.python-version }}, ${{ matrix.os }})
    # The type of runner that the job will run
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.7", "2.7"]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # get miniconda setup repo from conda-incubator 
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - name: Conda info
        shell: bash -l {0}
        run: conda info
      - name: Conda list
        shell: pwsh
        run: conda list
