# This is a basic workflow that is manually triggered

name: tests

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Use mamba to handle conda installs in a faster way.
# mamba-version accepts a version string x.y (including "*").
# It requires you specify conda-forge as part of the channels, ideally with the highest priority.
jobs:
  tests:
    name: tests
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.9
          mamba-version: "*"
          channels: conda-forge, bioconda, r
          channel-priority: true
          environment-file: mamba-environment.yml
          activate-environment: rseq
        env:
          GHKEY: ${{ secrets.GHKEY }}
      - name: Setup RSeq
        run: |
          conda activate rseq
          pip install .
          RSeqCLI
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test with coverage + pytest
        run: |
          bash tests/download_test_data.sh
          pip install pytest
          pip install pytest-cov
          pytest --cov=./ --cov-report=xml
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: 'ffe81218-3385-4ec1-aac1-62f348161b04'
          directory: ./coverage/reports/
          env_vars: OS,PYTHON
          files: ./coverage1.xml,./coverage2.xml
          flags: unittests
          name: codecov-umbrella
          path_to_write_report: ./coverage/codecov_report.txt
          verbose: true
